Create git tips
EddieJaoudeCommunity/support pull request #465
Opened 2020-11-29 16:28 UTC by nhcarrigan

Signed-off-by: nhcarrigan <nhcarrigan@gmail.com>

closes #ISSUE-NO

#### What does this PR do?

Creates a `tips` folder and adds a `git.md` file for git-related tips.

#### Description of Task to be completed?

(I'm actually not sure what goes here...)

#### How can this be manually tested?

Read it! 😁 
- Confirm that the commands are correct and work as intended
- Definitions are clear and accurate
- Steps can be followed in an actual project.

#### Any background context you want to provide?

Came from a discussion with @eddiejaoude and @Vyvy-vi on the Discord server.

#### What is the relevant issue link?

There isn't one. 🙂 

#### Screenshots (if appropriate)

#### Questions:

2020-11-29 17:52 UTC, Vyvy-vi approved these changes

2020-12-01 15:46 UTC, AkshayaKulasekaran commented on tips/git.md
> +- `repository`: A repository is like a folder that holds a project's files, but unlike other folders a repository is tracked for changes by `git`.
Might want to mention that `repo` is a short form of `repository` or vice versa for future convinience

2020-12-01 15:47 UTC, AkshayaKulasekaran commented on tips/git.md
> +- `fork`: A forked repository is a "copy" of a repository that has references to the original. GitHub will track differences between a fork and a source for you, and show the number of different comm
Might want to add `clone` and the difference between forking and cloning

2020-12-01 18:02 UTC, AkshayaKulasekaran requested changes
I think it looks good! Just added two suggestions for clarity

2020-12-02 00:50 UTC, nhcarrigan commented
@AkshayaKulasekaran I've added the terms you requested - are the definitions clear enough? 🙂

2020-12-02 23:07 UTC, AllanRegush commented
Where is the original discussion for this change?
I don't have my context for this. I'll leave this for @eddiejaoude.

2020-12-02 23:20 UTC, AllanRegush approved these changes
Looks Good :+1: Thank You

2020-12-02 23:26 UTC, merged

2020-12-05 22:04 UTC, eddiejaoude commented
Great team effort, thank you all 👍