DOCS: added description for bug template
EddieJaoudeCommunity/support pull request #494
Opened 2020-12-04 13:43 UTC by Vyvy-vi

closes #468

#### What does this PR do?
adds a description to the Bug-template.
#### Description of Task to be completed?
NA
#### How can this be manually tested?
Yes, by copying the template to some test repo or at https://github.com/Vyvy-vi/Vyvy-vi/issues/new
#### Any background context you want to provide?
It would be better to have a description for this.
(might erase confusion while raising issues regarding the repo, rather than questions about the community)
#### What is the relevant issue link?
https://github.com/EddieJaoudeCommunity/support/issues/468
#### Screenshots (if appropriate)

#### Questions:
Can this be better phrased?

2020-12-04 14:16 UTC, dumbcoder7 requested changes

2020-12-04 14:16 UTC, dumbcoder7 commented on .github/ISSUE_TEMPLATE/bug.md
> +labels: 'bug'
```suggestion
labels: 'bug'
```
I dont think we need this line to change. The labels on the bug template works perfectly fine.

2020-12-04 14:52 UTC, dumbcoder7 submitted a review, later dismissed

2020-12-04 18:25 UTC, AllanRegush commented
I'm not sure if we need [BUG] in the title if we have the `Bug` label. 

What do you think?

2020-12-04 18:26 UTC, AllanRegush commented
Everything else looks good and adds value. 👍

2020-12-04 18:27 UTC, Vyvy-vi commented
Hmm the label kinda beats the point

2020-12-04 18:29 UTC, nhcarrigan requested changes

2020-12-04 18:29 UTC, nhcarrigan commented on .github/ISSUE_TEMPLATE/bug.md
> +<!--A clear and concise description of what the bug is.-->
```suggestion
<!--A clear and concise description of what the bug is.-->
```

If we're using a comment for this, let's remove the text.

2020-12-04 19:06 UTC, dumbcoder7 approved these changes

2020-12-05 15:43 UTC, nhcarrigan approved these changes
LGTM~! 🥳 

Thank you for your pull request! We look forward to additional contributions!

2020-12-06 04:30 UTC, AllanRegush approved these changes
Looks Good To Me 👍 Thank You

2020-12-06 04:30 UTC, merged

2020-12-06 10:57 UTC, eddiejaoude commented
Thanks all 👍